name: format

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: pip3 install .[dev]

    - name: Run --help
      run: |
        oj-template -h
        oj-prepare -h

    - name: Run pylint
      run: pylint --rcfile=setup.cfg onlinejudge_template onlinejudge_random onlinejudge_prepare tests setup.py

    - name: Run isort
      run: isort --check-only --diff onlinejudge_template onlinejudge_random onlinejudge_prepare tests setup.py

    - name: Run yapf
      run: yapf --diff --recursive onlinejudge_template onlinejudge_random onlinejudge_prepare tests setup.py

    - name: Run mypy
      run: mypy onlinejudge_template onlinejudge_random onlinejudge_prepare tests setup.py
